### ISSUE TITLE
Reorient, Style and make dashboard values live

### ISSUE THREAD

**Issue by Jfairfield1** [AZMAG/map-Health#6]
Re-position the dashboard ui at the bottom of the page centered.

Also, make the dashboard values match the live layer on the map.

**Comment by Jfairfield1** [comment]
Also, forgot to mention, this should have a minimize button.

**Comment by JackFairfield** [comment]
The dashboard to be much smaller,  show up in the bottom right corner of the screen and not inhibit the map when it comes up.
